### ISSUE TITLE
win10本地建了个emqtt broke使用这个sdk

### ISSUE THREAD

**Issue by limuzi2012** [zhangguanzhang/ESP8266_NONOS_SDK-mqtt-uart_set#1]
用show指令显示[10:54:56.541]收←◆ssid:TP-LINK_C32E0C
pwd:1858szyf
host:192.168.1.94
port:8083
hid:abcdefg
mqtt.user:test1
mqtt.pwd:test123456
MQTT: queuing publish, length: 18, queue size(40/2048)
MQTT: queuing publish, length: 18, queue size(60/2048)
然后就是一直显示这个
[10:56:32.472]收←◆Free memory
TCP: Connect to ip  192.168.1.94:8083
TCP: Reconnect to: 192.168.1.94:8083
MQTT: Connected to broker 192.168.1.94:8083
MQTT:Sending,type:1,id:0000
TCP: Sent
TCP: data received 158 bytes
TCP: Disconnected callback
MQTT: Disconnected

**Comment by zhangguanzhang** [comment]
你得写个mqtt的服务器地址，你这看样子客户端连不上服务器

2018-03-03 10:57 GMT+08:00 limuzi2012 <notifications@github.com>:

**Comment by limuzi2012** [comment]
端口写错了,应该是1883
